config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get 'users/:id' => 'pages#show', as: 'user_page'
  get 'items/new' => 'items#new', as:'item_new'
  get 'items', to: redirect('items/new')
  get 'items/:id' => 'items#show', as:'item_show'
  get 'items/:id/edit' => 'items#edit', as:'item_edit'
  patch 'items/:id' => 'items#update'
  post 'transaction' => 'item_transactions#create', as:'transaction'
  get 'transaction/:id/' => 'item_transactions#show', as:'transaction_show'
  get 'transactions/:id' => 'item_transactions#index', as: 'transaction_index'
  post 'transaction_comment/:id' => 'item_transaction_comments#create', as:'transaction_comment'
  get 'transaction_comment_delete/:id' => 'item_transaction_comments#destroy', as:'transaction_comment_delete'

  resources :users
  resources :items, only: [:create, :destroy]
  resources :items , only: [:create , :destroy ] do
        resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :body, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :comment, dependent: :destroy
  has_one :item_transaction, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader
  validates :user_id, presence: true
  validates :image, presence: true
  validate  :image_size
  validates :name, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :price, presence: true

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def image_size
    if image.size > 15.megabytes
      errors.add(:image, "should be less than 15MB")
    end
  end
end

app/models/item_transaction.rb
class ItemTransaction < ApplicationRecord
  belongs_to :item, class_name: "Item"
  belongs_to :seller, class_name: "User", foreign_key: 'seller_id'
  belongs_to :buyer, class_name: "User", foreign_key: 'buyer_id'
  has_many :item_transaction_comment, dependent: :destroy
end

app/models/item_transaction_comment.rb
class ItemTransactionComment < ApplicationRecord
  belongs_to :item_transaction
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :item, dependent: :destroy
  has_many :comment, dependent: :destroy
  has_many :seller_item_transaction, class_name: 'ItemTransaction', foreign_key: 'seller_id'
  has_many :buyer_item_transaction, class_name: 'ItemTransaction', foreign_key: 'buyer_id'
  has_many :item_transaction_comment, class_name: 'ItemTransactionComment', dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  VALID_EMAIL_REGEX = /\A[0-9]{2}[a-z]{2}[0-9]{3}[a-z]{1}@rikkyo.ac.jp\Z/
  validates :email, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   added_attrs = [ :username, :email, :password, :password_confirmation　]
   devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
   devise_parameter_sanitizer.permit :account_update, keys: added_attrs
   devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
 end

 private

 def logged_in_user
   unless logged_in?
     store_location
     flash[:danger] = "Please log in."
     redirect_to login_url
   end
 end
 def logged_in?
   !current_user.nil?
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @comment = @item.comment.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to item_show_path(@item)
    else
      redirect_to item_show_path(@item)
    end

  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
     redirect_to  request.referrer || root_url
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/item_transaction_comments_controller.rb
class ItemTransactionCommentsController < ApplicationController
  def create
    @transaction = ItemTransaction.find(params[:id])
    @transaction_comment = @transaction.item_transaction_comment.build(transaction_comment_params)
    @transaction_comment.user = current_user
    if @transaction_comment.save
      redirect_to transaction_show_path(@transaction.id)
    else
      redirect_to transaction_show_path(@transaction.id)
    end

  end

  def destroy
    @transaction_comment = ItemTransactionComment.find(params[:id])
    @transaction_comment.destroy
     redirect_to  request.referrer || root_url
  end

  private

  def transaction_comment_params
    params.require(:item_transaction_comment).permit(:body)
  end
end

app/controllers/item_transactions_controller.rb
class ItemTransactionsController < ApplicationController

  def create
    @transaction = ItemTransaction.new(transaction_params)
    @item = Item.find(@transaction.item_id)
    if @transaction.save!
      @item.update_attribute(:sold, true)
      @item.save!
      redirect_to transaction_show_path(@transaction.id)
    else
      render root_url
    end
  end

  def show
    @transaction = ItemTransaction.find(params[:id])
    @item_transaction_comment = ItemTransactionComment.new
  end

  def index
    @user = User.find(params[:id])
    @buy_transactions = ItemTransaction.where(buyer_id: @user.id)
    @sell_transactions = ItemTransaction.where(seller_id: @user.id)
  end

  private

  def transaction_params
    params.require(:item_transaction).permit(:item_id, :seller_id, :buyer_id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def new
    @item = current_user.item.build if logged_in?
  end

  def show
    @item = Item.find(params[:id])
    @user = User.find_by(id: @item.user_id)
    @comment = Comment.new
    @transaction = ItemTransaction.new
  end

  def create
    @item = current_user.item.build(item_params)
    if @item.save
      flash[:success]="出品に成功しました！"
      redirect_to root_url
    else
      flash[:success]="正しく入力されていません"
      render item_new_path
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find_by(id: params[:id])
    @user = @item.user
    if current_user == @user
      @item.update(item_params)
      @item.save
      redirect_to item_show_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    flash[:success] = "出品を取り消しました"
    redirect_to request.referrer || root_url
  end

  private

  def item_params
   params.require(:item).permit(:name, :content, :image, :price)
  end

  def correct_user
   @item = current_user.item.find_by(id: params[:id])
   redirect_to root_url if @item.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include ApplicationHelper
  def index
    @items = Item.where(sold: false).paginate(page: params[:page]).search(params[:search])
  end

  def show
    @user = User.find(params[:id])
    @items = @user.item.paginate(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/item_transaction_comments_helper.rb
module ItemTransactionCommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def current_user?(user)
    user == current_user
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/item_transactions/index.html.erb
<div class="buy_item_area">
  あなたが買った商品
  <% @buy_transactions.each do |transaction| %>
    <% @buy_item = Item.find(transaction.item_id) %>
    <%= link_to "#{@buy_item.name}", transaction_show_path(transaction.id) %>
  <% end %>
</div>
<div class="sell_item_area">
  あなたが売った商品
  <% @sell_transactions.each do |transaction| %>
    <% @sell_item = Item.find(transaction.item_id) %>
    <%= link_to "#{@sell_item.name}", transaction_show_path(transaction.id) %>
  <% end %>
</div>

app/views/item_transactions/show.html.erb
<div class="transaction-comment-area">
  <div class="comment-show-area">
    <% @transaction.item_transaction_comment.each do |comment| %>
      <p>
        <%= link_to "#{comment.user.username}" , user_page_path(comment.user.id) %>さん：<%= comment.body %>
        <%= link_to "削除", transaction_comment_delete_path(comment.id), data: { confirm: "本当に削除しますか？" } if current_user?(comment.user) %>
      </p>
    <% end %>
  </div>
  <div class="comment-form">
    <%= form_for @item_transaction_comment, url: transaction_comment_path(@transaction.id) do |f| %>
      <div class="field">
        <%= f.text_field :body, placeholder: "トークを入力" %>
      </div>
      <%= f.submit "送信", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/_error_message.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      未入力または無効な表記が<%= @item.errors.count %>点あります
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/items/_item.html.erb
<li class="col-md-5 col-xs-12 item-show panel panel-default item-index" id="item-<%= item.id %>">
  <div class="content panel-heading">
    <h3><%= item.name %></h3>
  </div>
  <div class="panel-body">
    <%= image_tag item.image.url if item.image? %>
    <h3><%= item.price %>円</h3>
  </div>
  <div class="panel-footer">
    <span class="timestamp">
      <span class="user">出品者<%= link_to "#{item.user.username}", user_page_path(item.user.id) %>さん</span>
      <%= time_ago_in_words(item.created_at) %>前に出品
    </span>
    <div class="item-footer-area"><%= link_to "詳しく見る", item_show_path(item.id) %>
    <% if current_user?(item.user) %>
      <%= link_to "削除", item, method: :delete, :class => "delete-button", data: { confirm: "本当に削除しますか？　一度削除すると元には戻せません。" } %>
    <% end %>
    </div>
  </div>
</li>

app/views/items/_item_form.html.erb
<%= form_for(@item) do |f| %>
  <%= render 'items/error_message' %>
  <div class="item-new-field">
    <div class="panel panel-default">
      <div class="panel-heading">出品用入力フォーム</div>
      <div class="panel-body">
        <div class="form-group">
          <label class="control-label">画像</label>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <label class="control-label">商品名</label>
          <%= f.text_field :name, :class => "form-control", placeholder: "商品名を正確に記入してください" %>
        </div>
        <div class="form-group">
          <label class="control-label">説明</label>
          <%= f.text_area :content, :class => "form-control instraction-area", placeholder: "商品の説明を記入してください" %>
        </div>
        <div class="form-group">
          <label class="control-label">値段（円）</label>
          <%= f.number_field :price, :class => "form-control", placeholder: "金額を半角数字で入力してください" %>
        </div>
      </div>
      <div class="panel-footer item-new-footer">
        <%= f.submit "出品する", class: "btn btn-primary", data: { confirm: "出品してよろしいですか？" } %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="form-group">
  <%= form_for(@item) do |f| %>
    <ul class="new_form_area">
      <li>画像<%= f.file_field :image %></li>
      <li>商品名<%= f.text_area :name, placeholder: "商品名を正確に記入してください" %></li>
      <li>説明<%= f.text_area :content, placeholder: "商品の説明を記入してください" %></li>
      <li>値段<%= f.number_field :price, placeholder: "金額を半角数字で入力してください" %></li>
    </ul>
    <%= f.submit "変更を保存", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/items/new.html.erb
<h1>出品する</h1>
<div class="row">
  <aside class="col-md-12">
    <section class="item-new-form-area">
      <%= render 'item_form' %>
    </section>
  </aside>
</div>

app/views/items/show.html.erb
<div class="item-show-area panel panel-default">
  <h2 class="panel-heading"><%= @item.name %></h2>
  <div class="content_area panel-body">
    <div class="image_area">
      <%= image_tag @item.image.url if @item.image? %>
    </div>
    <span>商品の説明　<span class="item-content-sentence"><%= @item.content %></span></span>
    <h3><%= @item.price %>円</h3>
  </div>
  <div class="panel-footer">
    <div class="buyer-name-area">
      <%= time_ago_in_words(@item.created_at) %>前に出品
      出品者 <%= link_to "#{@item.user.username}", user_page_path(@item.user.id) %>さん
    </div>
    <% if @item.sold == false %>
      <div class="buy-area">
        <%= form_for @transaction, url: transaction_path do |f| %>
          <%= f.hidden_field :item_id, value: @item.id %>
          <%= f.hidden_field :buyer_id, value: current_user.id %>
          <%= f.hidden_field :seller_id, value: @item.user.id %>
          <%= f.submit "予約", class: "btn btn-primary reserve-button", data: { confirm: "予約してよろしいですか？" } %>
        <% end %>
      </div>
    <% else %>
      <div class="sold-area">
        <p>この商品は募集していません</p>
      </div>
    <% end %>
    <div class="edit-area">
      <% if current_user?(@item.user) %>
      <%= link_to "編集", item_edit_path(@item.id) %>
      <%= link_to "削除", @item, method: :delete, data: { confirm: "本当に削除しますか？　一度削除すると元には戻せません。" } %>
      <% end %>
    </div>
  </div>
</div>
<div class="comment-show-area">
  <% @item.comment.each do |comment| %>
    <p><%= link_to "#{comment.user.username}" , @user %>さん： <%= comment.body %>
    <%= link_to "削除", [@item,comment], method: :delete, data: { confirm: "本当に削除しますか？" } if current_user?(comment.user) %></p>
  <% end %>
</div>
<div class="comment-form-area">
  <%= form_for([@item , @comment]) do |f| %>
    <div class="field">
      <%= f.text_field :body, placeholder: "コメントを入力" %>
    </div>
    <div class="comment-button">
      <%= f.submit "送信", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <p>by Toru Nagai</p>
    <ul>
      <li><a href="https://www.facebook.com/profile.php?id=100006495363798" target="_blunk"><i class="fa fa-facebook"></i></a></li>
      <li><a href="https://twitter.com/johnmanjiro3rd" target="_blunk"><i class="fa fa-twitter"></i></a></li>
      <li><a href="https://www.instagram.com/toru.nagai/" target="_blunk"><i class="fa fa-instagram"></i></a></li>
      <li><a href="mailto:johnmanjiro3rd@gmail.com"><i class="fa fa-envelope"></i></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
<div class="container">
  <%= link_to "rikkari", root_path, id: "logo" %>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "募集一覧", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "取引中の商品", transaction_index_path(current_user.id) %></li>
        <li><%= link_to "出品する", item_new_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            マイアカウント <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to current_user.username, user_page_path(current_user.id) %></li>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to '新規登録', new_user_registration_path %></li>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rikkari</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

    </div>

    <%= render "layouts/footer"%>

  </body>
</html>

app/views/pages/index.html.erb
<div class="col-md-12">
  <div class="search-form-area">
    <%= form_tag root_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search], placeholder: "商品名で検索してみよう" %>
        <%= submit_tag "検索", :class => "search-button", :name => nil %>
      </p>
    <% end %>
  </div>
  <h1>現在募集中の商品</h1>
  <% if @items.any? %>
    <h3>現在<%= @items.count %>個の商品が募集中！</h3>
    <ol class="items-index">
      <%= render @items %>
    </ol>
    <%= will_paginate @items %>
  <% else %>
    <h3>まだ出品してないよ〜</h3>
  <% end %>
</div>

app/views/pages/show.html.erb
<div class="col-md-12">
  <h1>この出品者の商品</h1>
  <% if @user.item.any? %>
    <h3>現在<%= @user.item.count %>個出品中です！</h3>
    <ol class="microposts">
      <%= render @items %>
    </ol>
    <%= will_paginate @items %>
  <% else %>
    <h3>まだ出品してないよ〜</h3>
  <% end %>
</div>